version: '3.8'
services:
  fluentd:
    build: ./fluentd
    container_name: fluentd
    links:
      - "es01"
    depends_on:
      - es01
    ports:
      - "9880:9880"
      - "9881:9881"
      - "9882:9882"
      - "9883:9883"
      - "9884:9884"
      - "9885:9885"
      - "9910:9910"
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - elastic

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: es01
    environment:
      - node.name=es01
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms2048m -Xms2048m"
      - xpack.security.enabled=false
    volumes:
    - type: bind
      source: "./elasticsearch/config/elasticsearch.yml"
      target: /usr/share/elasticsearch/config/elasticsearch.yml
      read_only: true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    expose:
      - "9200"
    ports:
      - "9200:9200"
    networks:
      - elastic
    
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.11.1
    volumes:
      - type: bind
        source: "./kibana/config/kibana.yml"
        target: /usr/share/kibana/config/kibana/yml
        read_only: true
    ports:
      - 5601:5601
    depends_on:
      - es01
    links:
      - "es01"
    networks:
      - elastic

networks:
  elastic:
    driver: bridge